### ISSUE TITLE
東京地区の MX2 のサービス ID が MX1 のものになる

### ISSUE THREAD

**Issue by steshi-git** [yoshinrt/tv-oukoku-iepg#10]
いつも便利に使わせていただいて、ありがとうございます。

MX2の番組を、当拡張機能を利用して、BuffaloのPCastTV4付属のPFulliEPG.exeで予約しようとすると、
チャンネルがMX1になってしまうようです。

手動でチャンネルを変えることはできるですが、今までそれに気が付かずに、MX1で予約録画してしまい、
目的の番組が録画できていませんでした。

**Comment by yoshinrt** [comment]
ご報告ありがとうございます．

当方 Tokyo MX を受信出来る環境がないので，お手数ですが試していただきたいことがあります．
お手元の環境で適当な MX2 の番組の *.tvpid をダウンロードしていただき，
(下記は例であり番組は何でも良いです)
```
Content-type: application/x-tv-program-digital-info; charset=shift_jis
version: 2
station: DFS05C38 ←★ここ
station-name: ＴＯＫＹＯ　ＭＸ２
year: 2020
month: 07
date: 12
start: 14:00
end: 18:00
program-title: [生]プロ野球　パ・リーグ応援宣言!ホークス中継2020
program-id: 123610202007121400
```

`station:` の `DFS05C38` を，
1. DFS05C39 に書き換えたとき
1. DFS05C3A に書き換えたとき

どちらが正しく Tokyo-MX2 を受信できますでしょうか?

**Comment by steshi-git** [comment]
ご連絡ありがとうございます。

DFS05C3A に書き換えたとき に、正しく予約プログラムで、MX2が選局されました。

2020年7月12日(日) 16:01 Yoshi NRT <notifications@github.com>:

**Comment by yoshinrt** [comment]
ご確認ありがとうございました．
修正して chrome ウエブストアに登録済み (バージョン 28) ですので，google の審査が終わって公開されるまでしばらくお待ち下さい．
