### ISSUE TITLE
スポーツライブ+でサービスIDエラー

### ISSUE THREAD

**Issue by telii** [yoshinrt/tv-oukoku-iepg#13]
スカチャンでサービスIDエラーが出ます

**Comment by yoshinrt** [comment]
ご連絡ありがとうございます．
具体的にどのチャンネルでエラーになるか，教えていただけませんでしょうか．
スポーツライブ+ でエラーになるのは確認できました．

**Comment by telii** [comment]
スポーツライブ+でエラーが出てたのですが
iepgが正常に表示されるようになりました
お騒がせいたしました

**Comment by yoshinrt** [comment]
スポーツライブ+ のエラーが正常になったのは，昨日修正して google に up した (ver.33) ので，それの影響です．
issue タイトルを スポーツ+ から スカチャン に修正されていたことに up してから気づいたので，その他の ch でもエラーなのかな? と思って質問させていただきました．
とにかく，正常に動いたようで良かったです．

**Comment by telii** [comment]
ありがとうございました
修正される前はタイトルやコメ欄にスポーツ+と書いて投稿すると勝手にスカチャンに変換されてしまうので戸惑いました
その他のchは正常です
テレビ王国の番組表は見やすいのでiepgが終了してしまってからⅠ年半困っていましたが
神拡張機能に出会えました
感謝です
