### ISSUE TITLE
シネフィルWOWOW→WOWOWプラス に変更

### ISSUE THREAD

**Issue by yoshinrt** [yoshinrt/tv-oukoku-iepg#14]
@telii さんから
https://github.com/yoshinrt/tv-oukoku-iepg/commit/8ae41331534d1d2853dea56bf817885e8537a6b0#commitcomment-44973361

**Comment by yoshinrt** [comment]
@telii さん
ご連絡ありがとうございました．
修正して chrome ウエブストアに登録済み (バージョン 34) ですので，google の審査が終わって公開されるまでしばらくお待ち下さい．

**Comment by telii** [comment]
修正ありがとうございました
WOWOWプラスでipegタグ確認できました
