### ISSUE TITLE
2022年3月開局の新BS3局対応

### ISSUE THREAD

**Issue by jojocat1205** [yoshinrt/tv-oukoku-iepg#18]
2022年3月開局の新BS3局について、対応をお願いします。
・「ＢＳ松竹東急」　260
・「ＢＳＪａｐａｎｅｘｔ」　263
・「ＢＳよしもと」　265
　
以上よろしくおねがいします。

**Comment by yoshinrt** [comment]
ご連絡ありがとうございました．
修正して chrome ウエブストアに登録済み (バージョン 40) ですので，google の審査が終わって公開されるまでしばらくお待ち下さい．

**Comment by jojocat1205** [comment]
対応ありがとうございました。
３局ともiEPGボタンで予約できることを確認しました。
