### ISSUE TITLE
難視聴対策用の station id が残っている (元タイトル: station id 間違い)

### ISSUE THREAD

**Issue by steshi-git** [yoshinrt/tv-oukoku-iepg#7]
ここ最近使い始めた者です。
ありがたく使わせていただいていますが、東京地域の日テレを含むいくつかの局のstation idが間違っているようです。
日テレは、正しくは DFS00410 ですが、生成されたiepg.tvpidでは BSDT294 となっています。

ご参考
iEPG Version2 フォーマット解析 || 350ml.net
https://350ml.net/labo/iepg2.html

**Comment by yoshinrt** [comment]
ご連絡ありがとうございました．
難視聴対策 (地デジが受信できない地域用に地上波の番組を BS で放送するチャンネル) 用の station id が残ってしまっていたので，削除しました．

すでに chrome ウエブストアに登録済み (バージョン 24) ですので，google の審査が終わって公開されるまでしばらくお待ち下さい．

**Comment by steshi-git** [comment]
素早い対応ありがとうございます。
日テレでの動作を確認しました。

2019年12月14日(土) 12:18 Yoshi NRT <notifications@github.com>:
